# Generated by Django 4.1.7 on 2023-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
