# Generated by Django 4.1.7 on 2023-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
        migrations.AddField(
            model_name='listing',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
